# Generated by Django 3.0.7 on 2023-04-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Petitions',
        ),
    ]
