# Generated by Django 3.0.7 on 2023-04-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_auto_20230408_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.TextField(default='profile_images/default_profile.png'),
        ),
    ]
